<?php
require_once __DIR__ . '/../../session_config.php';
require_once dirname(dirname(dirname(dirname(__DIR__)))) . '/common/constants.php';
require_once DB_CONNECT_FILE;
require_once OPERATION_FILE;
require_once '../../../include/common_functions.php';

// Check permissions
if (!isset($_SESSION['user_id']) || !in_array($_SESSION['user_role'], ['super_admin', 'accountant'])) {
    http_response_code(403);
    echo json_encode(['status' => 'error', 'message' => 'Access denied']);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Validate Input
    $payment_id = $_POST['payment_id'] ?? null;
    $refund_amount = $_POST['amount'] ?? null;
    $reason = $_POST['reason'] ?? 'Administrative Refund';

    if (!$payment_id || !$refund_amount) {
        http_response_code(400);
        echo json_encode(['status' => 'error', 'message' => 'Missing required parameters']);
        exit;
    }

    try {
        // Fetch Payment Details
        $payment = $dbOps->selectOne('tbl_payments', ['*'], ['id' => $payment_id]);

        if (!$payment) {
            throw new Exception("Payment record not found");
        }

        if ($payment['status'] !== 'paid') {
            throw new Exception("Only paid transactions can be refunded. Current status: " . $payment['status']);
        }

        // Fetch API Config from env.config.php
        require_once __DIR__ . '/../../../../common/config/app-config.php';
        $config = getPaymentGatewayConfig('easebuzz');

        if (!$config) {
            throw new Exception("Payment gateway configuration not found in environment settings");
        }

        $merchant_key = $config['api_key'];
        $merchant_salt = $config['api_secret'];
        $env = $config['environment'] ?? 'prod';

        // Include EaseBuzz Library from backend
        require_once '../../common/easebuzz_loader.php';

        $easebuzzObj = new Easebuzz($merchant_key, $merchant_salt, $env);

        // Prepare Refund Parameters
        // txnid - Transaction ID generated by merchant (gateway_reference in our tbl_payments is EasePay ID, transaction_id is our txnid usually)
        // actually looking at easebuzz-webhook.php: 
        // $transaction_id (our db) comes from $webhook_data['udf3'] or similar?
        // No, in `payment-save.php` (assumed), we send `txnid`.
        // Let's assume `tbl_payments.transaction_id` maps to EaseBuzz `txnid`.

        // However, EaseBuzz `refund` API usually requires the `txnid` (Merchant Transaction ID) or `easepayid`.
        // The library `refund.php` likely maps params.

        // Common EaseBuzz Refund Params:
        // txnid: Unique transaction ID associated with the transaction.
        // refund_amount: Amount to be refunded.
        // phone: Customer phone (optional usually but library might want it)
        // email: Customer email
        // amount: Original transaction amount

        // We need to fetch the original order details to get email/phone/txnid if not in tbl_payments
        // tbl_payments has `transaction_id`.
        // Let's check `tbl_payment_orders` for email/phone if needed.

        $stmt = $conn->prepare("SELECT * FROM tbl_payment_orders WHERE payment_id = ?");
        $stmt->execute([$payment['gateway_reference']]); // gateway_reference stores easepayid usually.
        // Wait, `tbl_payments.transaction_id` is usually the Merchant Txn ID (e.g., TKN-...).

        // Let's fallback to student data if needed.
        $student = $op->selectOne('tbl_gm_std_registration', ['*'], ['id' => $payment['student_id']]);

        $postData = [
            "txnid" => $payment['transaction_id'],
            "refund_amount" => floatval($refund_amount),
            "phone" => $student['whatsapp_contact'] ?? '9999999999',
            "email" => $student['email'] ?? 'admin@example.com',
            "amount" => floatval($payment['amount'])
        ];

        // Call API
        $resultJson = $easebuzzObj->refundAPI($postData);
        $result = json_decode($resultJson, true);

        // Log the raw result for debugging
        // file_put_contents('refund_log.txt', print_r($result, true), FILE_APPEND);

        if (isset($result['status']) && $result['status'] == 1) {
            // Success (or Request Accepted)
            // EaseBuzz usually returns 'status' => 1 and data with 'refund_id'

            $refund_id = $result['data']['refund_id'] ?? ('REF-' . time());
            $refund_status = 'pending'; // Initially pending, webhook confirms success

            if (isset($result['data']['status']) && $result['data']['status'] == 'success') {
                $refund_status = 'success';
            }

            // Update refund tracking in tbl_refund_requests (consolidated - no separate tbl_refunds needed)
            $stmt = $conn->prepare("UPDATE tbl_refund_requests 
                                   SET request_status = ?, 
                                       gateway_refund_id = ?,
                                       gateway_reference = ?,
                                       refund_data = ?,
                                       processed_at = NOW(),
                                       processed_by = ?
                                   WHERE payment_id = ? AND student_id = ?
                                   ORDER BY created_at DESC LIMIT 1");
            $stmt->execute([
                $refund_status,
                $refund_id,
                $payment['gateway_reference'],
                $resultJson,
                $_SESSION['user_id'],
                $payment['id'],
                $payment['student_id']
            ]);

            // Update Payment Status to 'refund_initiated' or 'refunded'
            if ($refund_status == 'success') {
                $stmt = $conn->prepare("UPDATE tbl_payments SET status = 'refunded', remarks = CONCAT(remarks, ' | Refunded: ', ?) WHERE id = ?");
                $stmt->execute([$refund_amount, $payment['id']]);
                // Token fee refunded status is stored strictly in tbl_payments
            } else {
                $stmt = $conn->prepare("UPDATE tbl_payments SET status = 'refund_initiated', remarks = CONCAT(remarks, ' | Refund Initiated: ', ?) WHERE id = ?");
                $stmt->execute([$refund_amount, $payment['id']]);
            }

            echo json_encode(['status' => 'success', 'message' => 'Refund initiated successfully', 'refund_id' => $refund_id]);
        } else {
            // API Error
            $errorMsg = $result['data'] ?? 'Unknown Gateway Error';
            throw new Exception("Gateway Error: " . $errorMsg);
        }
    } catch (Exception $e) {
        http_response_code(500);
        echo json_encode(['status' => 'error', 'message' => $e->getMessage()]);
    }
}


